### ISSUE TITLE
Model has been downloaded but the SHA256 checksum does not not match

### ISSUE THREAD

**Issue by sjperry01** [rakuri255/UltraSinger#100]
Getting the below error after running this command:  `py UltraSinger.py -i https://www.youtube.com/watch?v=XzOvgu3GPwY`

This time I used the default large-v2 model but had tried it previously with medium - same result. This is on a Lenovo Windows 11 laptop and plenty of free disk space. Any thoughts?

```
[UltraSinger] Loading whisper with model large-v2 and cpu as worker
No language specified, language will be first be detected for each audio file (increases inference time).
Traceback (most recent call last):
  File "C:\ultrasinger\src\UltraSinger.py", line 893, in <module>
    main(sys.argv[1:])
  File "C:\ultrasinger\src\UltraSinger.py", line 800, in main
    run()
  File "C:\ultrasinger\src\UltraSinger.py", line 346, in run
    detected_language, transcribed_data = transcribe_audio()
  File "C:\ultrasinger\src\UltraSinger.py", line 447, in transcribe_audio
    transcribed_data, detected_language = transcribe_with_whisper(
  File "C:\ultrasinger\src\modules\Speech_Recognition\Whisper.py", line 33, in transcribe_with_whisper
    loaded_whisper_model = whisperx.load_model(
  File "C:\ultrasinger\.venv\lib\site-packages\whisperx\asr.py", line 333, in load_model
    vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
  File "C:\ultrasinger\.venv\lib\site-packages\whisperx\vad.py", line 47, in load_vad_model
    raise RuntimeError(
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the model.
[UltraSinger] 0:01:12.421 - End Program
```

**Comment by rakuri255** [comment]
Maybe your download model file is corrupted. 
Have you tried to re-download it?
Can you try another model? e.g. `tiny`

**Comment by sjperry01** [comment]
I have tried the download multiple times and with tiny and medium-en models as well as large-v2. Same error each time.

We tried on a different machine (desktop with a discrete GPU) and it works fine.

**Comment by rakuri255** [comment]
Seems the error comes from WhisperX.
I searched the issues and there are few that have the same thing but also have workarounds. -> https://github.com/m-bain/whisperX/issues?q=SHA256+checksum

What i found so far:
1. Since you dont have a CUDA GPU -> dont install the cuda torch dependencies
2. Maybe you have a CPU limitation. You CPU maybe cant compute `float16`. ->You can change it in UltraSinger with ` --whisper_compute_type  Change to "int8" if low on GPU mem (may reduce accuracy) >> ((default) is "float16" for cuda devices, "int8" for cpu)`
