### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Namluu07** [rakuri255/UltraSinger#104]
Hello,
since i reinstall windows the app doesn't work anymore. Before that it works perfectly (what an amazing app by the way, thanks you for this job)
Here what i get : 

[UltraSinger] 0:00:00.234 - Initialized...
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
[UltraSinger] Checking GPU support for tensorflow and pytorch.
[UltraSinger] tensorflow - using cuda gpu.
[UltraSinger] pytorch - using cuda gpu.
[UltraSinger] full automatic mode
[youtube] Extracting URL: https://www.youtube.com/watch?v=oSxqkER3N6Y
[youtube] UXU0_vRYYJI: Downloading webpage
[youtube] UXU0_vRYYJI: Downloading ios player API JSON
[youtube] UXU0_vRYYJI: Downloading android player API JSON
[youtube] UXU0_vRYYJI: Downloading m3u8 information
[UltraSinger] Searching song in musicbrainz
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1031, in _send_output
    self.send(msg)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 969, in send
    self.connect()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\.venv\lib\site-packages\musicbrainzngs\musicbrainz.py", line 497, in _safe_read
    f = opener.open(req)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\src\UltraSinger.py", line 858, in <module>
    main(sys.argv[1:])
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\src\UltraSinger.py", line 771, in main
    run()
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\src\UltraSinger.py", line 290, in run
    ) = download_from_youtube()
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\src\UltraSinger.py", line 637, in download_from_youtube
    (title_info, artist_info, year_info, genre_info) = get_music_infos(f"{artist} - {title}")
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\src\modules\musicbrainz_client.py", line 13, in get_music_infos
    artists = musicbrainzngs.search_artists(search_string)
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\.venv\lib\site-packages\musicbrainzngs\musicbrainz.py", line 935, in search_artists
    return _do_mb_search('artist', query, fields, limit, offset, strict)
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\.venv\lib\site-packages\musicbrainzngs\musicbrainz.py", line 782, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\.venv\lib\site-packages\musicbrainzngs\musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\.venv\lib\site-packages\musicbrainzngs\musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\.venv\lib\site-packages\musicbrainzngs\musicbrainz.py", line 690, in _mb_request
    resp = _safe_read(opener, req, body)
  File "D:\Jeux\UltraStarWorldParty\ultrasinger\UltraSinger-main\.venv\lib\site-packages\musicbrainzngs\musicbrainz.py", line 525, in _safe_read
    raise NetworkError(cause=exc)
musicbrainzngs.musicbrainz.NetworkError: caused by: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
[UltraSinger] 0:00:01.406 - End Program

If someone can help me.
Thank you

**Comment by rakuri255** [comment]
@Namluu07 Thanks for your feedback!
Your problem is that Musicbrainz is crashing. 
I just tested it on my machine with a fresh install and it works.

* Have you the issue with all songs?
* Maybe the Musicbrainz server was down? -> does it work now?

**Comment by Namluu07** [comment]
Thanks for your fast answer !
Yes i have this issue whith all songs
And i try again today, but still not working...
I'm a bit lost

**Comment by Namluu07** [comment]
Hi !
I solve the issue by downloading a AllInOne paquage of runtimes, .net, etc..
It works fine now, i don't now what was missing exactly, but it's fine.

thanks
