### ISSUE TITLE
oh uh i broke it....

### ISSUE THREAD

**Issue by D4ftchunk** [rakuri255/UltraSinger#124]
i was having a clean up on my system and ive now got this Error any advice please

Error opening input file C:\Users\ridle\Desktop\UltraSinger-main\src\output\The Weeknd, JENNIE, Lily - Rose Depp  (2)\cache\separated\htdemucs\The Weeknd, JENNIE, Lily - Rose Depp \vocals.wav.
Error opening input files: No such file or directory

Traceback (most recent call last):
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\ultrasinger.py", line 984, in <module>
    main(sys.argv[1:])
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\ultrasinger.py", line 883, in main
    run()
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\ultrasinger.py", line 371, in run
    denoise_vocal_audio(input_path, denoised_output_path)
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\ultrasinger.py", line 876, in denoise_vocal_audio
    ffmpeg_reduce_noise(input_path, output_path)
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\modules\Audio\denoise.py", line 35, in ffmpeg_reduce_noise
    raise ffmpeg_exception
  File "C:\Users\ridle\Desktop\UltraSinger-main\src\modules\Audio\denoise.py", line 27, in ffmpeg_reduce_noise
    ffmpeg.input(input_file_path)
  File "C:\Users\ridle\Desktop\UltraSinger-main\.venv\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by rakuri255** [comment]
@D4ftchunk can you try it again with a new version?

**Comment by rakuri255** [comment]
No answer = it works
