### ISSUE TITLE
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded

### ISSUE THREAD

**Issue by DT05YT** [rakuri255/UltraSinger#130]
i tried this, and first attempt at it resulted in this:
```
(.venv) C:\Users\me\Downloads\UltraSinger-main\src>UltraSinger.py -i "song.mp3"

[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.9
[UltraSinger] *****************************
[UltraSinger] Checking GPU support for tensorflow and pytorch.
[UltraSinger] tensorflow - using cuda gpu.
[UltraSinger] pytorch - using cuda gpu.
[UltraSinger] full automatic mode
[UltraSinger] Searching song in musicbrainz
[UltraSinger] cant find title whip in song
[UltraSinger] No match found
[UltraSinger] Creating output folder. -> output\song (1)
[UltraSinger] Creating output folder. -> output\song (1)\cache
[UltraSinger] Separating vocals from audio with demucs and cuda as worker.
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\me\Downloads\UltraSinger-main\src\separated\htdemucs
Separating track output\song (1)\song.mp3
100%|██████████████████████████████████████████████████████████████████████| 181.35/181.35 [00:06<00:00, 26.18seconds/s]
[UltraSinger] Converting wav to mp3
[UltraSinger] Reduce noise from vocal audio with ffmpeg.
[UltraSinger] Converting audio for AI
[UltraSinger] Mute audio parts with no singing
[UltraSinger] Loading whisper with model large-v2 and cuda as worker
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.2.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\me\.cache\torch\whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.1+cu117. Bad things might happen unless you revert torch to 1.x.
[UltraSinger] Transcribing output\song (1)\cache\song_mute.wav
Traceback (most recent call last):
  File "C:\Users\me\Downloads\UltraSinger-main\src\UltraSinger.py", line 984, in <module>
    main(sys.argv[1:])
  File "C:\Users\me\Downloads\UltraSinger-main\src\UltraSinger.py", line 883, in main
    run()
  File "C:\Users\me\Downloads\UltraSinger-main\src\UltraSinger.py", line 392, in run
    detected_language, transcribed_data = transcribe_audio()
  File "C:\Users\me\Downloads\UltraSinger-main\src\UltraSinger.py", line 515, in transcribe_audio
    transcribed_data, detected_language = transcribe_with_whisper(
  File "C:\Users\me\Downloads\UltraSinger-main\src\modules\Speech_Recognition\Whisper.py", line 61, in transcribe_with_whisper
    result = loaded_whisper_model.transcribe(
  File "C:\Users\me\Downloads\UltraSinger-main\.venv\lib\site-packages\whisperx\asr.py", line 194, in transcribe
    language = language or self.detect_language(audio)
  File "C:\Users\me\Downloads\UltraSinger-main\.venv\lib\site-packages\whisperx\asr.py", line 252, in detect_language
    encoder_output = self.model.encode(segment)
  File "C:\Users\me\Downloads\UltraSinger-main\.venv\lib\site-packages\whisperx\asr.py", line 86, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded
```
What does it all mean

**Comment by Etidou** [comment]
Hey, @rakuri255 and @DT05YT I had exactly the same errors have you found a solution ?

**Comment by jonathanoh-94** [comment]
Hello,

I wanted to report that I'm facing a similar issue as described in this thread, particularly with Nvidia CUDA v11.8. It appears that the core of the problem might be related to compatibility or configuration issues with CUDA.

I am currently in the process of testing a workaround by forcing the operations to run on the CPU instead, using the --force_cpu True option, in hopes of bypassing the GPU acceleration issues tied to CUDA v11.8. I have not yet concluded if this approach will fully resolve the issue, but I wanted to share my ongoing experience with the community.

If anyone has encountered a similar situation and has insights, advice, or potential fixes, it would be greatly appreciated. I am eager to find a solution that allows for the smooth operation of UltraSinger without the hurdles posed by CUDA v11.8.

**Comment by ponelll** [comment]
Hello, 
I had the same issue with CUDA v11.8. After updating CUDA to v12.4, it works perfectly. I guess that's because the missing dll is cublas64_12.dll. CUDA v11.8 only has cublas64_11.dll.

**Comment by rakuri255** [comment]
Hi,

can you post your GPUs?
Did you install cuda with cu117 or cu118?

**Comment by Etidou** [comment]
Hey @rakuri255 My GPU is a Nvidia GEForce GTX 1080 and i'm running with cu117 !

**Comment by jonathanoh-94** [comment]
> Hi,
> 
> @Etidou , @DT05YT , @jonathanoh-94 , @ponelll can you post your GPUs? Did you install PyTorch with cu117, cu118 or cu121?

After updating to v12.4, it worked! Thank you !

**Comment by rakuri255** [comment]
I think the WhisperX trunk had some updates that breaks with pytorch 11.x

Is it solved for you all with `cu121`?

**Comment by Etidou** [comment]
It works for me too!

I just updated `pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu121` as you mentioned everything works fine now.

Thanks !

**Comment by jonathanoh-94** [comment]
I have another issues : 
[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.9
[UltraSinger] *****************************
[UltraSinger] Checking GPU support for tensorflow and pytorch.
[UltraSinger] tensorflow - using cuda gpu.
[UltraSinger] pytorch - using cuda gpu.
[UltraSinger] full automatic mode
[UltraSinger] Searching song in musicbrainz
[UltraSinger] Found Titel and Artist Le dernier des fainéants by Matheos
[UltraSinger] Found release year: 2022-01-21
[UltraSinger] Creating output folder. -> D:\Musique\Output Karaoke\Matheos - Le dernier des fainéants
[UltraSinger] Creating output folder. -> D:\Musique\Output Karaoke\Matheos - Le dernier des fainéants\cache
[UltraSinger] Separating vocals from audio with demucs and cuda as worker.
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\johco\AI\UltraSinger\src\separated\htdemucs
Separating track D:\Musique\Output Karaoke\Matheos - Le dernier des fainéants\Matheos - Le dernier des fainéants.mp3
[C:\vcpkg\buildtrees\mpg123\src\0d8db63f9b-3db975bc05.clean\src\libmpg123\id3.c:process_comment():584] error: No comment text / valid description?
  0%|                                                                     | 0.0/198.89999999999998 [00:00<?, ?seconds/s]C:\Users\johco\AI\UltraSinger\.venv\lib\site-packages\torch\nn\modules\activation.py:1196: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  return torch._native_multi_head_attention(
100%|██████████████████████████████████████████████| 198.89999999999998/198.89999999999998 [00:07<00:00, 27.79seconds/s]
[UltraSinger] Converting wav to mp3
Traceback (most recent call last):
  File "C:\Users\johco\AI\UltraSinger\src\UltraSinger.py", line 984, in <module>
    main(sys.argv[1:])
  File "C:\Users\johco\AI\UltraSinger\src\UltraSinger.py", line 883, in main
    run()
  File "C:\Users\johco\AI\UltraSinger\src\UltraSinger.py", line 354, in run
    convert_wav_to_mp3(instrumental_path, karaoke_output_path)
  File "C:\Users\johco\AI\UltraSinger\src\modules\Audio\convert_audio.py", line 21, in convert_wav_to_mp3
    sound = AudioSegment.from_wav(input_file_path)
  File "C:\Users\johco\AI\UltraSinger\.venv\lib\site-packages\pydub\audio_segment.py", line 808, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
  File "C:\Users\johco\AI\UltraSinger\.venv\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\johco\AI\UltraSinger\.venv\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\johco\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\johco\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

What the issue with the "FileNotFound"?

**Comment by rakuri255** [comment]
> It works for me too!
> 
> I just updated `pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu121` as you mentioned everything works fine now.
> 
> Thanks !

Isnt this CPU only?

**Comment by rakuri255** [comment]
When i use the latest cu121 with my RTX2080 i get Error: **cublas64_11.dll** instead of Error: **cublas64_12.dll**
