### ISSUE TITLE
index out of range when list is empty from musicbrainz

### ISSUE THREAD

**Issue by Nithrom** [rakuri255/UltraSinger#131]
Hi, i have a problem and i don't know whats wrong:

(.venv) C:\UltraSinger-main\src>py UltraSinger.py -i agapimu.mp3

[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.9
[UltraSinger] *****************************
[UltraSinger] Checking GPU support for tensorflow and pytorch.
[UltraSinger] tensorflow - using cuda gpu.
[UltraSinger] pytorch - using cuda gpu.
[UltraSinger] full automatic mode
[UltraSinger] Searching song in musicbrainz
Traceback (most recent call last):
  File "C:\UltraSinger-main\src\UltraSinger.py", line 984, in <module>
    main(sys.argv[1:])
  File "C:\UltraSinger-main\src\UltraSinger.py", line 883, in main
    run()
  File "C:\UltraSinger-main\src\UltraSinger.py", line 336, in run
    ) = infos_from_audio_input_file()
  File "C:\UltraSinger-main\src\UltraSinger.py", line 714, in infos_from_audio_input_file
    (title_info, artist_info, year_info, genre_info) = get_music_infos(search_string)
  File "C:\UltraSinger-main\src\modules\musicbrainz_client.py", line 14, in get_music_infos
    artist = artists['artist-list'][0]['name']
IndexError: list index out of range

**Comment by Nithrom** [comment]
I just replaced the .mp3 file to youtube link and it worked.

But then, at the end it shows this: 

[UltraSinger] Creating C:\UltraSinger-main\src\output\Ojete Calor Y Ana Belen  -  Agapimu Video Letra Karaoke (1)\Ojete Calor Y Ana Belen  -  Agapimu Video Letra Karaoke.txt from transcription.
Traceback (most recent call last):
  File "C:\UltraSinger-main\src\ultrasinger.py", line 984, in <module>
    main(sys.argv[1:])
  File "C:\UltraSinger-main\src\ultrasinger.py", line 883, in main
    run()
  File "C:\UltraSinger-main\src\ultrasinger.py", line 435, in run
    real_bpm, ultrastar_file_output = create_ultrastar_txt_from_automation(
  File "C:\UltraSinger-main\src\ultrasinger.py", line 651, in create_ultrastar_txt_from_automation
    ultrastar_writer.create_ultrastar_txt_from_automation(
  File "C:\UltraSinger-main\src\modules\Ultrastar\ultrastar_writer.py", line 75, in create_ultrastar_txt_from_automation
    gap = transcribed_data[0].start
IndexError: list index out of range

**Comment by rakuri255** [comment]
Oh nice found. 
Musicbrainz retuns an empty list because it can find your song and UltraSinger expects an entry.
Will fix that later. 

As a short workaround you could rename your .mp3 to "artist - song.mp3"
