### ISSUE TITLE
Cant get past wav to mp3

### ISSUE THREAD

**Issue by imnotresponding** [rakuri255/UltraSinger#133]
Hi there!
Installation on windows went well but I'm unable to get past the wav to mp3 step. I get the same error with --force_cpu True. 
Any ideas here?
//Imnotresponding

```
(.venv) E:\US\src>py UltraSinger.py -i "E:\US\s\Veronica Maggio - Pa en buss.mp3"

[UltraSinger] *****************************
[UltraSinger] UltraSinger Version: 0.0.9
[UltraSinger] *****************************
[UltraSinger] Checking GPU support for tensorflow and pytorch.
[UltraSinger] tensorflow - using cuda gpu.
[UltraSinger] pytorch - using cuda gpu.
[UltraSinger] full automatic mode
[UltraSinger] Searching song in musicbrainz
[UltraSinger] cant find title på en buss in veronica maggio  pa en buss
[UltraSinger] No match found
[UltraSinger] Creating output folder. -> E:\US\s\output\Veronica Maggio - Pa en buss
[UltraSinger] Creating output folder. -> E:\US\s\output\Veronica Maggio - Pa en buss\cache
[UltraSinger] Separating vocals from audio with demucs and cuda as worker.
[UltraSinger] Converting wav to mp3
Traceback (most recent call last):
  File "E:\US\src\UltraSinger.py", line 984, in <module>
    main(sys.argv[1:])
  File "E:\US\src\UltraSinger.py", line 883, in main
    run()
  File "E:\US\src\UltraSinger.py", line 354, in run
    convert_wav_to_mp3(instrumental_path, karaoke_output_path)
  File "E:\US\src\modules\Audio\convert_audio.py", line 21, in convert_wav_to_mp3
    sound = AudioSegment.from_wav(input_file_path)
  File "E:\US\.venv\lib\site-packages\pydub\audio_segment.py", line 808, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
  File "E:\US\.venv\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "E:\US\.venv\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "E:\Program\Python\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program\Python\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by rakuri255** [comment]
Hi,
I think there is an naming issue where UltraSinger gets confused.
Can you try as it with an different .mp3 name?

**Comment by Brawdogger** [comment]
Has anyone else ran into this issue an found a solution, seem to be encountering this a lot and haven't been able to find a solution
