### ISSUE TITLE
PyTorch compatibility issue since newer update

### ISSUE THREAD

**Issue by perc4** [rakuri255/UltraSinger#167]
```bash
Successfully installed torch-2.0.1+cu117 torchaudio-2.0.2+cu117 torchvision-0.15.2+cu117
(.venv) # python -c "import torch; print(torch.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1187, in <module>
    from .functional import *  # noqa: F403
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 7, in <module>
    from .. import functional as F
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 19, in <module>
    from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/_jit_internal.py", line 40, in <module>
    import torch.distributed.rpc
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/distributed/__init__.py", line 58, in <module>
    from .distributed_c10d import *  # noqa: F403
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 35, in <module>
    from torch.autograd.profiler import record_function
  File "/UltraSinger/.venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 334, in <module>
    if not torch._C._autograd_init():
AttributeError: module 'torch.autograd.graph' has no attribute 'GradientEdge'
```

**Comment by rakuri255** [comment]
Does the CPU installation working?
