### ISSUE TITLE
Some HF alignment models not recognized?

### ISSUE THREAD

**Issue by A2Sumie** [rakuri255/UltraSinger#179]
I edited alignment.py to try some non-default wav2vec2 models but some just won't get recognized.
reazon-research/japanese-wav2vec2-base
rinna/japanese-wav2vec2-base
these are indeed wav2vec2 models so i don't understand.
```
Can't load tokenizer for 'reazon-research/japanese-wav2vec2-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'reazon-research/japanese-wav2vec2-base' is the correct path to a directory containing all relevant files for a Wav2Vec2CTCTokenizer tokenizer.
Error loading model from huggingface, check https://huggingface.co/models for finetuned wav2vec2.0 models
Traceback (most recent call last):
  File "C:\Users\kaito\Anaconda3\envs\whisperX\lib\site-packages\transformers\models\wav2vec2\processing_wav2vec2.py", line 52, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\kaito\Anaconda3\envs\whisperX\lib\site-packages\transformers\processing_utils.py", line 465, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\kaito\Anaconda3\envs\whisperX\lib\site-packages\transformers\processing_utils.py", line 511, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "C:\Users\kaito\Anaconda3\envs\whisperX\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 858, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\Users\kaito\Anaconda3\envs\whisperX\lib\site-packages\transformers\tokenization_utils_base.py", line 2070, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'reazon-research/japanese-wav2vec2-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'reazon-research/japanese-wav2vec2-base' is the correct path to a directory containing all relevant files for a Wav2Vec2CTCTokenizer tokenizer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\wx\whisperx\whisperx\alignment.py", line 84, in load_align_model
    processor = Wav2Vec2Processor.from_pretrained(model_name)
  File "C:\Users\kaito\Anaconda3\envs\whisperX\lib\site-packages\transformers\models\wav2vec2\processing_wav2vec2.py", line 64, in from_pretrained
    tokenizer = Wav2Vec2CTCTokenizer.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\kaito\Anaconda3\envs\whisperX\lib\site-packages\transformers\tokenization_utils_base.py", line 2070, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'reazon-research/japanese-wav2vec2-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'reazon-research/japanese-wav2vec2-base' is the correct path to a directory containing all relevant files for a Wav2Vec2CTCTokenizer tokenizer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\kaito\anaconda3\envs\whisperX\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx', 'console_scripts', 'whisperx')())
  File "d:\wx\whisperx\whisperx\transcribe.py", line 188, in cli
    align_model, align_metadata = load_align_model(align_language, device, model_name=align_model)
  File "d:\wx\whisperx\whisperx\alignment.py", line 89, in load_align_model
    raise ValueError(f'The chosen align_model "{model_name}" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)')
ValueError: The chosen align_model "reazon-research/japanese-wav2vec2-base" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)
```

**Comment by A2Sumie** [comment]
Sorry this is for whisperX. Why did I sent it here...
