### ISSUE TITLE
Not working with GPU crepe

### ISSUE THREAD

**Issue by BanCrash** [rakuri255/UltraSinger#213]
```
[UltraSinger] Pitching with crepe and model full and cuda as worker
2024-12-28 11:10:39.490569: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-28 11:10:39.662955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9
2024-12-28 11:10:49.690401: W tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.0KiB (rounded to 1280)requested by op ScratchBuffer
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
2024-12-28 11:10:49.694493: I tensorflow/core/common_runtime/bfc_allocator.cc:1033] BFCAllocator dump for GPU_0_bfc
2024-12-28 11:10:49.695577: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (256):  Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.695713: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (512):  Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.695822: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (1024):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.695916: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (2048):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.695945: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (4096):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.695969: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (8192):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.695993: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (16384):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696016: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (32768):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696038: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (65536):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696060: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (131072):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696083: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (262144):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696106: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (524288):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696129: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (1048576):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696151: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (2097152):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696173: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (4194304):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696195: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (8388608):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696217: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (16777216):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696240: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (33554432):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696262: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (67108864):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696284: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (134217728):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696306: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Bin (268435456):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2024-12-28 11:10:49.696331: I tensorflow/core/common_runtime/bfc_allocator.cc:1056] Bin for 1.2KiB was 1.0KiB, Chunk State:
2024-12-28 11:10:49.696354: I tensorflow/core/common_runtime/bfc_allocator.cc:1094]      Summary of in-use Chunks by size:
2024-12-28 11:10:49.696375: I tensorflow/core/common_runtime/bfc_allocator.cc:1101] Sum Total of in-use chunks: 0B
2024-12-28 11:10:49.696395: I tensorflow/core/common_runtime/bfc_allocator.cc:1103] total_region_allocated_bytes_: 0 memory_limit_: 0 available bytes: 0 curr_region_allocation_bytes_: 0
2024-12-28 11:10:49.696421: I tensorflow/core/common_runtime/bfc_allocator.cc:1109] Stats:
Limit:                               0
InUse:                               0
MaxInUse:                            0
NumAllocs:                           0
MaxAllocSize:                        0
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2024-12-28 11:10:49.696475: W tensorflow/core/common_runtime/bfc_allocator.cc:491] <allocator contains no memory>
Traceback (most recent call last):
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 752, in <module>
    main(sys.argv[1:])
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 591, in main
    run()
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 179, in run
    process_data.pitched_data = pitch_audio(process_data.process_data_paths)
  File "C:\Programas\UltraSinger\src\UltraSinger.py", line 565, in pitch_audio
    pitched_data = get_pitch_with_crepe_file(
  File "C:\Programas\UltraSinger\src\modules\Pitcher\pitcher.py", line 23, in get_pitch_with_crepe_file
    return get_pitch_with_crepe(audio, sample_rate, model_capacity, step_size)
  File "C:\Programas\UltraSinger\src\modules\Pitcher\pitcher.py", line 33, in get_pitch_with_crepe
    times, frequencies, confidence, activation = crepe.predict(
  File "C:\Programas\UltraSinger\.venv\lib\site-packages\crepe\core.py", line 255, in predict
    activation = get_activation(audio, sr, model_capacity=model_capacity,
  File "C:\Programas\UltraSinger\.venv\lib\site-packages\crepe\core.py", line 185, in get_activation
    model = build_and_load_model(model_capacity)
  File "C:\Programas\UltraSinger\.venv\lib\site-packages\crepe\core.py", line 62, in build_and_load_model
    y = Conv2D(f, (w, 1), strides=s, padding='same',
  File "C:\Programas\UltraSinger\.venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Programas\UltraSinger\.venv\lib\site-packages\keras\backend.py", line 2100, in random_uniform
    return tf.random.stateless_uniform(
tensorflow.python.framework.errors_impl.FailedPreconditionError: {{function_node __wrapped____EagerConst_device_/job:localhost/replica:0/task:0/device:GPU:0}} Failed to allocate scratch buffer for device 0
```

Command: `UltraSinger.py -i <youtube link> -o C:\Downloads\ --whisper large-v3 --disable_karaoke True
`

I've installed using bat installer with cuda.

**Comment by rakuri255** [comment]
It says that you are run out of memory.
Since 2024, I have made some memory optimizations and changed other things.
Please test it again, and if the problem persists, feel free to create a new ticket.
