### ISSUE TITLE
option --align-model not recognized

### ISSUE THREAD

**Issue by stripu** [rakuri255/UltraSinger#66]
Got an issue where when i use the --align-model option i get the following output:

(.venv) F:\UltraSinger>UltraSinger.py -i https://www.youtube.com/watch?v=ClMKh6Z8VXA --align-model "infinitejoy/wav2vec2-large-xls-r-300m-romanian"
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "F:\UltraSinger\UltraSinger.py", line 785, in <module>
    main(sys.argv[1:])
  File "F:\UltraSinger\UltraSinger.py", line 710, in main
    init_settings(argv)
  File "F:\UltraSinger\UltraSinger.py", line 719, in init_settings
    opts, args = getopt.getopt(argv, short, long)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\getopt.py", line 93, in getopt
    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\getopt.py", line 157, in do_longs
    has_arg, opt = long_has_args(opt, longopts)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\getopt.py", line 174, in long_has_args
    raise GetoptError(_('option --%s not recognized') % opt, opt)
getopt.GetoptError: option --align-model not recognized

The only way I managed to get it working is by adding the model name directly in the Settings.py file.

**Comment by rakuri255** [comment]
Its "--align_model" not "--align-model" :)

**Comment by crowbardoctor** [comment]
I still get this error.

**Comment by rakuri255** [comment]
@crowbardoctor It has been renamed to `--whisper_align_model`
