### ISSUE TITLE
Installing error on M1 Mac

### ISSUE THREAD

**Issue by Loewe1000** [rakuri255/UltraSinger#79]
Hi,

when trying to install the dependencies on my MacBook with
pip install -r requirements.txt
I get the following error:
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.12.0 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0)
ERROR: No matching distribution found for tensorflow~=2.12.0

I know what the error means, but can't find any solution for finding a matching tensorflow version.

I use the 13" M1 MacBook Pro 2020 with macOS Ventura 13.4.1.
Any help is much appreciated.

**Comment by rakuri255** [comment]
Sorry mate. Never used a Mac. 
Maybe @bohning can help you?

I can only provide this: [what-is-the-proper-way-to-install-tensorflow-on-apple-m1-in-2022](https://stackoverflow.com/questions/72964800/what-is-the-proper-way-to-install-tensorflow-on-apple-m1-in-2022). 

Seems they solve this by just install it with pip install tensorflow-macos.
Can you test this?

**Comment by rakuri255** [comment]
Since there is no response, i think `pip install tensorflow-macos` done the job

**Comment by SacredSkull** [comment]
Not related to the main issue, but I have a fork that adds some optimisation for Apple M chip users - you get a fairly decent speed up where possible - fastwhisper doesn't seem to be Silicon optimised but the other parts are.

https://github.com/SacredSkull/UltraSinger-Apple-Silicon-Optimised

At some point I'll hopefully raise a PR to add that in without affecting x86 users (currently my fork _only_ will work on Silicon) - but for any Apple Mx chip users feel free to use for now.

**Comment by rakuri255** [comment]
@SacredSkull hey cool work! Thanks!
Just PR it when you think your ready to.
I cant test it since i dont have an Mac.

Maybe @bohning can try it.

**Comment by bohning** [comment]
Unfortunately I am still on Intel Mac, so I think it makes no sense that I test it.

**Comment by duarteveia** [comment]
Hey ! I've Tested with a M3 macbook , the forked mac version and im having a bit of trouble.

when i input the url on the loop.sh i get 

Running UltraSinger.py with input: https://youtu.be/2ptnRzcBnZM and nice value: 2
unknown command: python. Perhaps you have to reshim?

i tried everything but still haven't figure out.

**Comment by rakuri255** [comment]
There was already an installation support thanks to @magicus.
See here: https://github.com/rakuri255/UltraSinger/commit/f97fbd7de82e53ad75df35f77bac6dd4296aa4fd

I currently fixing the installer and moving to uv.
The current solution has a broken dependencie chain and cant be installed anymore.

**Comment by devton-here** [comment]
I was able to install it on my Macbook M1 with MacOS 15 (git commit hash: e07cb9024236e495c76817aef5339d4ccdc05355)

Installtion:

```
pyenv local 3.12
pip install uv
install/CPU/macos_cpu.sh
cd src
python UltraSinger.py -i ...
```

I was able to load and convert some videos from YouTube, even if I got errors during the process.

But for some videos from YouTube it's not working, maybe that is related to this:

> WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one

Here is a log for which video from YouTube doesn't work:

```
python UltraSinger.py -i 'https://www.youtube.com/watch?v=TBT6edKlNj4' --whisper tiny                                                                                      [14:28:41]

[UltraSinger] *********************************
[UltraSinger] UltraSinger Version: 0.0.13.dev15
[UltraSinger] *********************************
[UltraSinger] Checking GPU support.
[UltraSinger] pytorch - there are no cuda devices available -> Using cpu.
[UltraSinger] ----------------------
[UltraSinger] FFmpeg - using /opt/homebrew/bin/ffmpeg
[UltraSinger] FFprobe - using /opt/homebrew/bin/ffprobe
[UltraSinger] ----------------------
[UltraSinger] Option: Notes will be quantized to the detected musical key
[UltraSinger] Full Automatic Mode
[youtube] Extracting URL: https://www.youtube.com/watch?v=TBT6edKlNj4
[youtube] TBT6edKlNj4: Downloading webpage
WARNING: [youtube] No supported JavaScript runtime could be found. Only deno is enabled by default; to use another runtime add  --js-runtimes RUNTIME[:PATH]  to your command/config. YouTube extraction without a JS runtime has been deprecated, and some formats may be missing. See  https://github.com/yt-dlp/yt-dlp/wiki/EJS  for details on installing one
[youtube] TBT6edKlNj4: Downloading android vr player API JSON
ERROR: [youtube] TBT6edKlNj4: This video is not available
Traceback (most recent call last):
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1698, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1833, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 763, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/extractor/youtube/_video.py", line 4027, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1275, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] TBT6edKlNj4: This video is not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/dev/UltraSinger/src/UltraSinger.py", line 904, in <module>
    main(sys.argv[1:])
  File "/Users/user/dev/UltraSinger/src/UltraSinger.py", line 741, in main
    run()
  File "/Users/user/dev/UltraSinger/src/UltraSinger.py", line 163, in run
    process_data = InitProcessData()
                   ^^^^^^^^^^^^^^^^^
  File "/Users/user/dev/UltraSinger/src/UltraSinger.py", line 485, in InitProcessData
    ) = download_from_youtube(settings.input_file_path, settings.output_folder_path, settings.cookiefile)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/dev/UltraSinger/src/modules/Audio/youtube.py", line 90, in download_from_youtube
    (artist, title) = get_youtube_title(input_url, cookiefile)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/dev/UltraSinger/src/modules/Audio/youtube.py", line 23, in get_youtube_title
    result = ydl.extract_info(
             ^^^^^^^^^^^^^^^^^
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1687, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1716, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1154, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Users/user/dev/UltraSinger/.venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1093, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] TBT6edKlNj4: This video is not available
```

**Comment by rakuri255** [comment]
@devton-here thanks for the info.
Seems your issue is more related to the yldp package.
